name: jp_image_to_dict
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  http: ^1.2.0
  image: ^4.1.4
  image_picker: ^1.0.7
  pasteboard: ^0.2.0
  provider: ^6.1.1
  super_clipboard: ^0.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  lints: ^3.0.0

flutter:
  uses-material-design: true
